development:
  clients:
    default:
      database: consumer_api_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: consumer_api_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      database: consumer_api_production
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 5
